#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       pycurl
# >> macros
%{!?python_sitelib: %define python_sitelib %(%{__python} -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")}
# << macros

Summary:    cURL library module for Python
Version:    7.19.5.3
Release:    1
Group:      Development/Languages/C++
License:    LGPL/MIT
URL:        http://pycurl.sourceforge.net/
Source0:    %{name}-%{version}.tar.gz
BuildRequires:   python3-devel
BuildRequires:   gcc
BuildRequires:	 libcurl-devel
BuildRequires:   openssl-devel

Requires:        openssl-devel
Requires:	     python3-devel
Requires:		 libcurl-devel

%description
This module provides Python bindings for the cURL library.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build

# >> build pre
export PYCURL_SSL_LIBRARY=openssl

python3 setup.py build
# << build pre



# >> build post
# << build post

%install
python3 setup.py install --root $RPM_BUILD_ROOT

# >> install post
# << install post

%pre
# >> pre
# << pre

%preun
# >> preun
# << preun

%files
%defattr(-,root,root,-)
%{python_sitelib}/*
%doc /usr/share/doc/%{name}/*
# >> files
# << files
